### ISSUE TITLE
Display the settings modal

### ISSUE THREAD

**Issue by Julien-Decoen** [shannonhochkins/ha-component-kit#100]
First, thanks a lot for this amazing project. It's rocks ! 🙌

**Is your feature request related to a problem? Please describe.**
Nop

**Describe the solution you'd like**
As on the lovelace ui, i'd like to display the settings form for an entity to edit those settings.

<img width="400" alt="image" src="https://github.com/shannonhochkins/ha-component-kit/assets/22341879/04d54ce7-81cd-4960-80bc-5ade98e5d684">

Do you think it's possible ? :)

**Comment by shannonhochkins** [comment]
Hey man! Thankyou!

I purposely omitted the "update" logic for devices and entities as this is something that home assistant handles quite well, it can easily be done and the support is there already (callApi method from useHass) where you can make a post request to update an entity!

What things did you want to update specifically? I'm just not sure (at this point) if it should be the responsibility of hakit :)

**Comment by shannonhochkins** [comment]
We can do the name / icon pretty easily, changing the entity ID is possible but it then becomes a bit more of a challenge for th3 developer side

I am actively working on a home assistant addon to do all that Lovelace can do and a lot more, but I have a lot going on back home and finding it hard to find time to work on it, but please be patient :)

**Comment by Julien-Decoen** [comment]
Thanks for you quick answer. I think your project is very cool, especially to hide the complexity of HA for my family. But they could wan't to change some entities settings from this simple ui.

> What things did you want to update specifically?

Everything that could change the ui : 
- Name
- Icon
- isHidden / isDisabled
- Area

The use case could be : 
I want to change the area related to my speaker because I move it on another room. 

> I am actively working on a home assistant addon to do all that Lovelace can do and a lot more, but I have a lot going on back home and finding it hard to find time to work on it, but please be patient :)

It looks interesting. I'm running HA on Docker Core version. But i'd like to run it inside HA too :)

**Comment by shannonhochkins** [comment]
Okay cool, I'll have a think about what this might look like! I agree a few of these things might be beneficial for sure

**Comment by Julien-Decoen** [comment]
Thanks a lot ! (and sorry for my bad english 😇)

**Comment by shannonhochkins** [comment]
I will close this ticket as it's not an issue but more of a feature request - please keep feature requests under the discussions area :)
