### ISSUE TITLE
Full example code similar to Demo dashboard

### ISSUE THREAD

**Issue by timota** [shannonhochkins/ha-component-kit#103]
**Is your feature request related to a problem? Please describe.**
I'm not a developer but would like to test your dashboard. It will be good to have an full example code similar to your demo dashboard, where user can simply change entities to his own. And as a result to play with components. 

Thanks.

**Comment by shannonhochkins** [comment]
I would suggest watching a few basic react video tutorials on YouTube before giving this a crack! The source code for the demo is under the storybook directory and you'll see the demo file in there!

**Comment by shannonhochkins** [comment]
I will be building an addon for home assistant to make this easier for users such as yourself but I'm still a while off completing that part!
