### ISSUE TITLE
Docs and npm create are bonked

### ISSUE THREAD

**Issue by koriwi** [shannonhochkins/ha-component-kit#106]
just check the docs here. same happens when you run the npm create. the default code basically has 2 lines swapped. https://shannonhochkins.github.io/ha-component-kit/?path=/docs/components-cards-areacard--docs

this happened to me today after i followed your docs :)

btw. very nice project. love it and want to def. contribute when i know it a bit better! so feel free to shoot me over the commits that fix the issues i opened so i can get into it faster!

**Comment by shannonhochkins** [comment]
Thankyou! Happy to help along the way, I've deployed a change to fix the docs for the area card, as well as a new version of hakit/create as i fixed this issue months ago but never released... fail.... Can you confirm it's okay now?

**Comment by shannonhochkins** [comment]
Release: https://github.com/shannonhochkins/ha-component-kit/releases/tag/3.0.5

**Comment by koriwi** [comment]
hey, lemme do a quick check :)
