### ISSUE TITLE
DevContainer

### ISSUE THREAD

**Issue by koriwi** [shannonhochkins/ha-component-kit#109]
Issue for tracking discussion and testing of dev containers.

Proposed goal:
- provide dev container
- DevContainer includes home assistant demo instance
- no additional setup needed inside the container

**Comment by shannonhochkins** [comment]
I'm interested in seeing the benefits of setting something like this up! Keen for a demo to highlight the benefits vs what I have currently!

**Comment by koriwi** [comment]
will do my best :) but it can take a while and i will probably need your help at some point

**Comment by shannonhochkins** [comment]
No drama!

**Comment by koriwi** [comment]
Sooo. I hope i finally have some time this weekend to work on this issue :)

**Comment by shannonhochkins** [comment]
Sweet as man! I still don't quite understand the whole point/benefit, maybe you can explain it a bit more with the pros/cons to me? :)

**Comment by shannonhochkins** [comment]
I'll close this seeing as it's been inactive for a while now @koriwi - feel free to open a PR if you do end up helping out :)
