### ISSUE TITLE
Adding order number for AreaCards in SidebarCard

### ISSUE THREAD

**Issue by amasolov** [shannonhochkins/ha-component-kit#111]
**Is your feature request related to a problem? Please describe.**
At this point Areas are added to SideBarCard in reverse order of how they are defined in the source code. However at the same time, they are getting placed in direct order in the main placeholder. It's reproducible if I follow the example from the docs:

https://shannonhochkins.github.io/ha-component-kit/?path=/docs/components-cards-sidebarcard--docs

**Describe the solution you'd like**
Use the same order in both places or adding a priority or order number to arrange them in SidebarCard

**Comment by shannonhochkins** [comment]
Hey! I will take a look at this when I can! Thanks for this!

**Comment by shannonhochkins** [comment]
@amasolov - I've now added a new prop to the `SidebarCard` component called `sortSidebarMenuItems` which receives a sorting function, it will receive all the menu items just before it's about to render, this will allow you to sort based on alpha betical, or something completely custom.

See - https://github.com/shannonhochkins/ha-component-kit/pull/115/files for reference, released under version 3.1.2
