### ISSUE TITLE
Area Summary Card

### ISSUE THREAD

**Issue by dignifiedquire** [shannonhochkins/ha-component-kit#112]
Quite a few themes/setups have an overview of the area, with some quick actions potentially. E.g. showing the lights are on/off current temperature etc. I was wondering if that would be an enhancement you are interested in

**Comment by shannonhochkins** [comment]
It's actually something I've been implementing as a complete theme to be purchased for home assistant, I hadn't thought about introducing it for hakit as it does feel user specific, I have just tried to create the building blocks to achieve anything really! But I don't quite think an overview should be part of the card itself

**Comment by shannonhochkins** [comment]
Will close this as I've not heard of anything else from you mate
