### ISSUE TITLE
License status

### ISSUE THREAD

**Issue by dignifiedquire** [shannonhochkins/ha-component-kit#113]
Hey, thanks for the cool work on this! 

Some of the code seems to be licensed under the standard ISC license, but the core component seems to have a non standard, custom license. Could you clarify the exact status here?

**Comment by shannonhochkins** [comment]
Thanks for point this out, I'll fix this up and reply to you here when I can!

**Comment by shannonhochkins** [comment]
Fixed under latest version 3.1.2
