### ISSUE TITLE
Allow numeric value for media_content_id

### ISSUE THREAD

**Issue by benjaminandrews38** [shannonhochkins/ha-component-kit#114]
**Is your feature request related to a problem? Please describe.**
media_player.play_media only accepts a string value for media_content_id. Some smart TV integrations allow channel selection by integer value. This is supported by home assistant.

**Describe the solution you'd like**
It would be nice if the type was string|number, and I hope this isn't too onerous 

**Describe alternatives you've considered**
 I'm not sure of any alternative solutions

**Additional context**
I'm trying to create a tv remote component with an integrated program guide. So far in testing, only an LG webOS tv has worked with string channel values. 

It works fine using useStore().connection.sendMessage, so not a huge priority.

**Comment by shannonhochkins** [comment]
Hey mate! Unfortunately, the types for all services are generated from the services schema which is incorrect in a few locations, this is a simple one I can implement something in the next release!

**Comment by shannonhochkins** [comment]
Fixed as of version 3.1.2 - types now defined as `string | number` as requested! For refernce - https://github.com/shannonhochkins/ha-component-kit/pull/115/files
