### ISSUE TITLE
Entity icon only updates when refreshing the page

### ISSUE THREAD

**Issue by Brewno88** [shannonhochkins/ha-component-kit#117]
First of all, thank you so much for creating and maintaining this, I love it and it's amazing how easy you made it to use! 🤩

**Describe the bug**
I've noticed that the Entity's Icon inside `entity.attributes.icon` doesn't get updated based on the state of the entity until I refresh the page, although everything else gets updated correctly automatically from the webhook (i.e. state changes from `off` to `on` but the icon remains `"mdi:motion-sensor-off"`).
I tried to find an issue in my code but I tried the `useEntity()` hook in a plain component and log the returned entity.

**To Reproduce**
1. In any component use the `useEntity()` hook and console log the returned entity
2. Trigger the state change
3. Check the new logs after the state change, and notice the new state value but in `attributes.icon` the icon remains unchanged
4. Refresh the page and now you should see the new icon based on the new state

**Expected behavior**
The icon should update without the need to refresh the page

**Screenshots / code examples**
My example below is with a motion binary_sensor but the same result happens with contact sensors.

<img width="846" alt="Screenshot 2024-02-14 at 22 39 24" src="https://github.com/shannonhochkins/ha-component-kit/assets/44366545/5a178384-af92-4543-bd54-5155f9bba81f">

**System Info (please complete the following information):**
 - Visual Studio Code
 - Chrome/Arc
 - npm version 9.6.3
 - node version 18.13.0

**Comment by shannonhochkins** [comment]
Hey legend! Thanks for the kind words!

Which component are you using? It seems a bit unlikely that you're seeing a state change but not a render change to reflect the state

Would you mind sharing your react code?

**Comment by shannonhochkins** [comment]
Oh sorry, I just saw the after reload in red in the screenshot, I'll see if I can replicate! Which version of HA are you running?

**Comment by Brewno88** [comment]
Thanks for looking 😄 
I'm using:
- HA Core 2024.2.1

**Comment by shannonhochkins** [comment]
Hey mate - thanks for reporting this! It was across all entities that derive an icon from entity state when there's no custom icon defined in in Home Assistant, Nice find!

This has been merged under PR #119 and released version [3.1.3](https://github.com/shannonhochkins/ha-component-kit/releases/tag/3.1.3)

Would you mind testing under the latest versions and report back to me please :)

**Comment by Brewno88** [comment]
Thanks very much for looking into this so quickly.

I've just tried it and everything works perfectly 🙌
