### ISSUE TITLE
Prevent sidebar/group collapsing

### ISSUE THREAD

**Issue by kdkavanagh** [shannonhochkins/ha-component-kit#131]
Unless I missed it somewhere, it would be great to have an option to prevent the sidebar or a group from being collapsed (and remove the associated icons).

**Comment by shannonhochkins** [comment]
Please provide more context of your issue, I do not have enough information to be able to help you here, if you're after a way for it to start open, use the `startOpen` prop.

**Comment by kdkavanagh** [comment]
Sorry, I'm looking for a way to open by default (using that parameter you noted) _and_ to prevent it from being collapsed by the user (ie remove the collapse arrow/hamburger menu button, essentially). 

Happy to implement it, just making sure it doesn't already exist somewhere and I just missed it

**Comment by shannonhochkins** [comment]
I see! Unfortunately no, that feature to hide the toggle doesn't exist currently, shouldn't be too hard to add! Feel free to create an issue and PR!

**Comment by shannonhochkins** [comment]
You could always just hide the header of the sidebar with css using the cssStyles attribute!

**Comment by shannonhochkins** [comment]
I've merged your PR - will release with the next set of changes!
