### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by kdkavanagh** [shannonhochkins/ha-component-kit#138]
I'm not familiar with the framer-motion library, so unclear how to best implement this, but, I'd like to disable animations for some (but not all) of the elements in my dashboard.  For example, the modal entry/exit animations seem to be too intensive for my cheap tablet, but button animations work well

**Comment by shannonhochkins** [comment]
Keep an eye on https://github.com/shannonhochkins/ha-component-kit/issues/128 as this will contain the features you're after, you can replace the animations completely or disable them, I'll include a simple `disableAnimation` flag for you

**Comment by shannonhochkins** [comment]
If you don't want to wait, you can also disable them now by adding this to your root application AROUND <HassConnect

```
import { MotionConfig } from "framer-motion"

export function App({ children }) {
  return (
    <MotionConfig reducedMotion="user">
      <HassConnect hassUrl={HASSURL}>{children}</HassConnect>
    </MotionConfig>
  )
}
```

**Comment by shannonhochkins** [comment]
There's a new release now available that you can disable the complex animations if need be!

```
import { ModalProvider } from '@hakit/components';
import { HassConnect } from '@hakit/core';
export function App({ children }) {
  return (
    <HassConnect hassUrl={HASSURL}> // check the available options for reducedMotion
      <ModalProvider options={{
         reducedMotion: 'always'
      }}>{children}</ModalProvider>
    </MotionConfig>
  )
}
```

Could you please check it out and let me know if it's all working for you?

**Comment by shannonhochkins** [comment]
Release as a part of [3.2.0](https://github.com/shannonhochkins/ha-component-kit/releases/tag/3.2.0)
