### ISSUE TITLE
Authorization request after each page refresh

### ISSUE THREAD

**Issue by Navatusein** [shannonhochkins/ha-component-kit#146]
**Describe the bug**
Whenever the page is refreshed, HassConnect redirects to the authorization page. Despite the fact that there is a hassTokens entry in local storage.

**To Reproduce**
For me, it appears every time the page is refreshed.

**System Info (please complete the following information):**
 - IDE: WebStorm
 - Browser Chrome
 - npm version: 10.5.0
 - node version: 20.11.1

**Comment by shannonhochkins** [comment]
Interesting - could you please provide me some replicatable steps or upload a zip file containing a setup that you have with the issue?

**Comment by Navatusein** [comment]
I created an empty project using Vite and have the same problem. [React Test.zip](https://github.com/shannonhochkins/ha-component-kit/files/15481102/React.Test.zip) The problem manifests itself locally and after assembly. I haven’t tried loading it into HA yet. My browser is Chrome 125.0.6422.78 and I also tried it in Edge but everything is the same there.

**Comment by shannonhochkins** [comment]
Were you trying an IP address as the hassUrl? I'll check out your zip next time I'm on the computer

**Comment by Navatusein** [comment]
I pasted the url with the ssl directly into HassConnect

**Comment by shannonhochkins** [comment]
Curious - looking in your local storage, the hassUrl value in local storage, does it match EXACTLY to you hassUrl input in the HassConnect prop? The only reason i ask, is because if there's a trailing slash or some difference in the URL it will redirect to the auth page as it may think it's a new URL to authenticate.

**Comment by Navatusein** [comment]
That's exactly the problem. Thanks for your help.
