### ISSUE TITLE
access to HA without logging in (use token)

### ISSUE THREAD

**Issue by cheddarwhizzy** [shannonhochkins/ha-component-kit#147]
**Is your feature request related to a problem? Please describe.**
I'm using a kiosk app on a wall mounted iPad. The cache gets cleared and I have to re-login. 

**Describe the solution you'd like**
I'd like to be able to provide a long lived token rather that log in with username and password

**Describe alternatives you've considered**
I've attempted `allow_bypass_login` under `trusted_networks` without success. 

**Additional context**
this is an internal application I run on my home network, so there's no security risk for my use-case

**Comment by shannonhochkins** [comment]
It's something i've often thought about, providing both options so thanks for the request - will have this out with the next release!

**Comment by constantindjonkam** [comment]
Will be so useful for the desktop app I'm building as HA won't allow me to redirect to non-http(s) scheme. Can't wait for this

**Comment by shannonhochkins** [comment]
I'll probably release a major version and make this the new default - ironically I already use this method for the deployment script so would be good to consolidate and have a singular workflow

I'm still focusing on multi lingal which will be complete this week, then i can move onto this

**Comment by shannonhochkins** [comment]
FYI - This has been complete and will be released within the next week with a bunch of other changes :)
