### ISSUE TITLE
Card title and description

### ISSUE THREAD

**Issue by gmartenscb** [shannonhochkins/ha-component-kit#150]
Hello and good morning,

I would like to suggest to swap the meaning of the `title` and `description`.
As to me, I would have expected the `title` to be on top, bigger, and in a more prolific fond.

![image](https://github.com/shannonhochkins/ha-component-kit/assets/79847451/0e6b1db7-11f8-4ebb-a9d7-2c029d5658bd)

**Comment by shannonhochkins** [comment]
This is something that's bothered me too - There's multiple different layouts with this card, however I'll see if I can make some more sense of it - it is intentionally smaller in font-size for longer entity names, however you're probably right it may make more sense to increase it slightly regardless and let the user control the size if need be - There will be a pretty large update coming this weekend:

https://github.com/shannonhochkins/ha-component-kit/pull/149

**Comment by shannonhochkins** [comment]
I agree with you, and it'll be in the next release!
