### ISSUE TITLE
Deploy docs update: SSH add-on

### ISSUE THREAD

**Issue by gmartenscb** [shannonhochkins/ha-component-kit#153]
The current documentation on "[Retrieving SSH Credentials](https://shannonhochkins.github.io/ha-component-kit/?path=/docs/introduction-deploying--docs#retrieving-ssh-credentials)" references the **Terminal & SSH addon**. 
While this is a viable add-on, community-wide it is suggested to use **[Advanced SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh)** instead.

I think it is wise to also provide documentation for this add-on, as it is slightly different from the one provided.
And it gave me some (very minor) issues while setting it up myself.

1. The _username_ has to be set to `root` (default is `hassio`).
2. The `sftp` flag has to be set to `true` (default is `false`, and `true` requires the _username_ to be `root`).

![image](https://github.com/shannonhochkins/ha-component-kit/assets/79847451/d945750a-9815-4773-911b-c2f11d2a6894)

**Comment by shannonhochkins** [comment]
Have updated & tested myself - all works fine

**Comment by gmartenscb** [comment]
Need a review? Can't really see where you did it in a PR / branch. Otherwise I can mark it as resolved.

**Comment by shannonhochkins** [comment]
It's all good, this PR has over 200 files changed which goes against everything I stand for, but that's open source for ya 😉 here's the link the doc changes you suggested!
