### ISSUE TITLE
Theme provider flashes

### ISSUE THREAD

**Issue by gmartenscb** [shannonhochkins/ha-component-kit#154]
**Describe the bug**
The theme provider is very flashy, both in the [Demo on Storybook](https://shannonhochkins.github.io/ha-component-kit/?path=/story/introduction-demo--default) as well as on local development.

**To Reproduce**
1. Go to https://shannonhochkins.github.io/ha-component-kit/?path=/story/introduction-demo--default
2. Click on the theme provider
3. Click on the "Dark Mode"
4. See it flash

**Screenshots / code examples**

https://github.com/shannonhochkins/ha-component-kit/assets/79847451/890f43ac-14ed-4dd4-8c83-1b9bb0c018c2

**System Info (please complete the following information):**
 - Same result in Brave, Chrome and Firefox

**Comment by shannonhochkins** [comment]
I'll close this one as I've already fixed it as a part of the next big release, thanks for raising it though!
