### ISSUE TITLE
window is not defined when upgrading to 1.0.13

### ISSUE THREAD

**Issue by element-software** [shannonhochkins/ha-component-kit#16]
I have a fully working dashboard and I've just upgraded to hakit/components v1.0.13 and hakit/core v1.0.11 - I made no other changes, and when I run `npm run dev` I'm getting the dreaded `window is not defined` error.

![image](https://github.com/shannonhochkins/ha-component-kit/assets/81567707/9f6a01aa-3925-44e2-bf35-c09a41f46014)

If I revert back to hakit/components v1.0.7 and hakit/core v1.0.4 I am able to `npm install` and `npm run dev` with no issues. I would like to use the ClimateCard :( 

Any idea as to why this would be the issue

Many thanks for your great work, I'm trying to understand the codebase so I can hopefully contribute to this.

**Comment by shannonhochkins** [comment]
Hi @element-software , would you mind providing replicatable steps? What version of node/npm are you using, what bundler?

I do test this before i release and I hadn't seen this issue before, but i did make a few core changes would could have impacted, but if you can point me in the right direction on how to replicate it i'll sort it out for you :)

**Comment by element-software** [comment]
Hi @shannonhochkins  sorry I did not provide this in my first post.

I'm using Node v18.16.1 and npm v9.7.2. It's a boilerplate Nextjs app (npx create next app with typescript), so everything is pretty much standard out of the box config. I've only added Tailwind to it, plus hakit/core and hakit/components.

I've done the usual delete node_modules and re-install etc. but no go unfortunately. I'm gonna spin up a fresh app and give it another try and will update you.

Again I can't express my gratitude enough to see your great work, I also commented on your Reddit post (my username is l19bal on Reddit). Very excited to make use of these components to build beautiful dashboards in a way I understand better (I'm a senior software engineer, and I don't like YAML aka Lovelace).

Thanks!

**Comment by shannonhochkins** [comment]
I can replicate with a very basic nextjs app - leave it with me I'll have it solved today for you :)

**Comment by shannonhochkins** [comment]
I believe this may have something to do with how nextjs decides what is a client/server component, are you using the 'use client' directive? I don't know a whole lot about nextjs, but i was able to replicate it initially, even when including the use client directive it would say it can't find the window object, this may cause issues storing the tokens on local storage or using the RoomCard hash links

Either way, I've just published new versions of core/components and the issue has been resolved (at least in my simple test) - please let me know if you're seeing issue's 

Thankyou for your kind words! Any more feedback / suggestions please throw them my way! I'm doing my best to ensure this is a seamless project with little errors but it's obviously hard to catch everything :)

**Comment by shannonhochkins** [comment]
@element-software have you managed to test it out yet?

**Comment by element-software** [comment]
Hi @shannonhochkins apologies for the delay. Yes I've updated them as below:

```
    "@hakit/components": "^1.0.17",
    "@hakit/core": "^1.0.14",
```

It all seems to be working as before! Thank you for this!!

**Comment by shannonhochkins** [comment]
Awesome! Thankyou
