### ISSUE TITLE
Deps missing after fresh install

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [shannonhochkins/ha-component-kit#162]
**Describe the bug**
After a fresh install, with npm i @hakit/core @hakit/components -D, no deps from these packages was installed

**To Reproduce**
1. Install deps
2. Implement HassConnect and ThemeProvider
3. Error shows up

**System Info (please complete the following information):**
 - IDE VScode
 - Browser Chrome
 - npm version 10
 - node version 20

**Additional context**
![image](https://github.com/user-attachments/assets/97246d33-381b-4645-bb4c-510a0ce134f7)

**Comment by shannonhochkins** [comment]
Don't install -D, that might be your problem!

**Comment by shannonhochkins** [comment]
Closing as there's been no further comms
