### ISSUE TITLE
Issues with use on mobile

### ISSUE THREAD

**Issue by mattmagin** [shannonhochkins/ha-component-kit#165]
**Describe the bug**
So I have just installed this and it is absolutely amazing. However before I get underway with configuring my dashboards, I get an error on my mobile device viewing the dashboard via the hakit add-on.

```
Unable to connect to Home Assistant, please check the URL: "Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS."
```

So 2 questions:
1. Have you figured out how to get around this
2. What's the best way to get this working fully on mobile? Ideally I want this to present as a 'proper' dashboard so I can set it as a default on my profiles.

Even if you have any leads on how to resolve these lemme know and I am happy to poke around the codebase myself and try to figure it out.

**Comment by shannonhochkins** [comment]
Hey mate, sorry didn't see this! Did you manage to solve it?

If not, sounds like a certificate issue by the error message, this error message is reported by the homeassistant js websocket package, not my package so I'd say have a look through that repo and see if the error gives you any leads!

**Comment by mattmagin** [comment]
@shannonhochkins Nah I haven't yet - but I also haven't really spent time on it since the weekend. Sweet - thanks I'll have a look through it when I have time - I am really want to get this to work - as I would rather write react than yaml!!

Have you managed to get this working on mobile through a dashboard?
Happy for you to close this issue if you want - or leave it open and I will report back when I have something.

**Comment by shannonhochkins** [comment]
My dashboard runs fine on my phone (android), my wife's phone (ios) and our wall tablet through the addon, I suspect it's something else based on your message! 

How is homeassistant exposed to the Web? Are you using nabucasa?

**Comment by shannonhochkins** [comment]
Additionally, are you using the hassurl and token approach with the HassConnect component?
