### ISSUE TITLE
Bump minimum react version

### ISSUE THREAD

**Issue by kdkavanagh** [shannonhochkins/ha-component-kit#167]
After pulling in the past ~5mths of changes, I discovered that the weather card nested inside a Sidebar would throw an error related to the weather card's resize detector (`cannot unpack 'width' as it's undefined`).  Updating react from 18.2 -> 18.3.1 fixed the issue.

ha-component-kit has a minimum version of `18.x` but probably now needs to be `18.3.x`

**Comment by shannonhochkins** [comment]
Fixed with latest [release](https://github.com/shannonhochkins/ha-component-kit/releases/tag/4.0.4)
