### ISSUE TITLE
Cannot open when added to Home Screen

### ISSUE THREAD

**Issue by pdhruv93** [shannonhochkins/ha-component-kit#52]
I have deployed the page to my Home assistant instance and I now have the URL for my dashboard.
I can access the URL from the browser normally.
But when I add it to the Home screen from Safari on iPhone, I get 403 Forbidden error rightaway, and nothing loads.
Is it something Home assistant related?

Update: tried adding the Home assistant normal URL to my home screen, it loads but everytime I close it, it asks credentials. So is it so when added to home screen, the browser engine is not able to maintain credentials. Is there some workaround with this library?

**Comment by shannonhochkins** [comment]
Sounds like it's not storing the tokens with local storage, can you try chrome please?

**Comment by pdhruv93** [comment]
Same issue with chrome as well, I think on iPhones all browsers uses safari engine behind the scenes, so the problem would be same on all browsers.

**Comment by shannonhochkins** [comment]
That doesn't seem correct, however what you can try is to include something in one of your components, to get the local storage value `localStorage.getItem('hassTokens')` and dump the response of that into one of your root component, ie

```
function App() {

    return <>
        {localStorage.getItem('hassTokens')}
    </>
}
```

Check this first on your browser to make sure you're seeing it, then check on your mobile

or add an alert in your javascript

alert(`Local storage is: ${typeof window.localStorage}`)

Sorry, bit hard to test this one for you as it does work fine on my phone and my wifes (android and iphone)

**Comment by shannonhochkins** [comment]
For context

```
export function saveTokens(tokens: AuthData | null) {
  tokenCache.tokens = tokens;

  if (!tokenCache.writeEnabled && extractSearchParam("storeToken") === "true") {
    tokenCache.writeEnabled = true;
  }

  if (tokenCache.writeEnabled && typeof storage !== "undefined") {
    try {
      storage.hassTokens = JSON.stringify(tokens);
    } catch (err: unknown) {
      // write failed, ignore it. Happens if storage is full or private mode.
    }
  }
}
```

this is the saveTokens function in the @hakit/core package

it could potentially be hitting the catch block here, you could  try putting an alert inside the catch block as well in your node_modules/@hakit/core/ (in cjs or js) whatever you're using, which i realise will be difficult as it's minified but it might help identify the issue

**Comment by pdhruv93** [comment]
"bit hard to test this one for you as it does work fine on my phone and my wifes (android and iPhone)" --> did you check when adding the page to home screen?

**Comment by shannonhochkins** [comment]
I believe that's what my wife has setup but I'll check with her

**Comment by shannonhochkins** [comment]
You can also plug your phone into your computer and remote debug with Chrome or safari, might be faster if there's already an error being thrown in the console

**Comment by pdhruv93** [comment]
I will check if it is just something on my device.

**Comment by shannonhochkins** [comment]
Let me know I'm happy to help :)

**Comment by shannonhochkins** [comment]
What was the issue?

**Comment by pdhruv93** [comment]
Not sure, didn't have much time for debugging. Any how I won't be using from the home screen shortcut, was just checking that. If I debug in future, I will put the reason/answer here.

**Comment by shannonhochkins** [comment]
Okay then no problems
