### ISSUE TITLE
Card for Calendar entries

### ISSUE THREAD

**Issue by pdhruv93** [shannonhochkins/ha-component-kit#56]
Can we have a card to show future events from a Calendar(Google) entity or if there is already some card that can be used for similar purposes.

**Comment by shannonhochkins** [comment]
Can you please include feature requests in the discussions area, Calendar card is on the roadmap it's listed on storybook, but it's not the highest on my priority list

**Comment by shannonhochkins** [comment]
![Screenshot 2023-10-16 at 3 43 08 pm](https://github.com/shannonhochkins/ha-component-kit/assets/5105002/13ac9e7d-7ba9-4544-a95d-7c37bbdf90b5)
Still a work in progress, but i've started to get something going for you @pdhruv93

**Comment by pdhruv93** [comment]
Thanks, waiting for a long time

**Comment by shannonhochkins** [comment]
Yes I've made it identical to the Lovelace one

**Comment by shannonhochkins** [comment]
Can you please install the latest and let me know what you think / if you have any problems @pdhruv93 ?

CalendarCard has been released, if you run into problems with the new api flow, there's documentation of what's needed to install here:  https://shannonhochkins.github.io/ha-component-kit/?path=/docs/hooks-usehass-callapi--docs

As the calendar entries are only retrievable (in a nice format) from the rest api, i had to include a new hook from the useHass store called "callApi"

This does mean that you may need to follow the steps on the mentioned page to get this to work :)

**Comment by rensknoors** [comment]
Was just working on my own calendar card when I found this.

Seems to work just fine except for one small Typescript error. `options` seems to be required but all the properties of `RequestInit` are optional.
I can work around this by using passing an empty object of course.

Great work!

**Comment by shannonhochkins** [comment]
Thanks for the feedback! I'm glad there's only a few small bugs there, easy fixes! 

I'll have those sorted in the next patch, ive started working on a camera card and I've had some success so far retrieving live streams, but if you notice anything else reach out!
