### ISSUE TITLE
Page fails to render without error

### ISSUE THREAD

**Issue by ifuller1** [shannonhochkins/ha-component-kit#9]
If I add any delay to the rendering the HassConnect it fails to render at all. 

My guess is there's a onload listener or similar used to check the localstorage after which you redirect to the auth page? 

I've got some scripts running to set the auth token but this causes a delay hence the issue. 

To work around it I've refreshed the page after a slight delay and it seems happy but it's obviously not ideal.

Cheers!

**Comment by shannonhochkins** [comment]
I have noticed this and it's on my list! It's an order of operations issue, I will have this addressed as soon as i can :)

**Comment by ifuller1** [comment]
Thanks. Is it possible to see the original source for core? I couldn't find
the repo.

**Comment by shannonhochkins** [comment]
The source is in this repo @ifuller1 under packages/core :)

**Comment by shannonhochkins** [comment]
Feel free to submit a pull request if I don't solve it in time! But i will take a look at it early next week!

**Comment by ifuller1** [comment]
🤦 - I'd made the ASSumption that it was a separate repo for each npm
package. Thanks.

**Comment by shannonhochkins** [comment]
No problems! 

What i had planned to do is reference how home-assistant handles auth here: https://github.com/home-assistant/frontend/blob/cd19894ab096faef764c5cd220f572133f6fc445/cast/src/launcher/layout/hc-connect.ts#L234 and mimic the same behaviour through @hakit/core

**Comment by shannonhochkins** [comment]
I have just published a new version of @hakit/core (v1.0.9) - changes [here](https://github.com/shannonhochkins/ha-component-kit/pull/12)

This should address your delay issue you were having, however it would be good to understand exactly what you were trying to hit the issue

I believe I've solved a few bugs with the authentication flow (listed in the PR linked above) however please let me know if you're still having issues!

**Comment by shannonhochkins** [comment]
I will close this ticket due to inactivity - the issue has been resolved :)

**Comment by ifuller1** [comment]
Apologies, I've been away. I did try with the new library but I still have to trigger a refresh. 

To be clear I'm setting local storage before I render any react. 

What I haven't done is checked the vite cache is cleared or used core source and a debugger. So best to close for now and I'll re-open with more data if necessary.

Cheers

**Comment by shannonhochkins** [comment]
That's okay! You might need to share a bit of your setup to help me identify the issue, what are you setting in local storage before rendering? HassConnect should do that for you
